// src/pages/workbench/WorkbenchShell.svelte
<script lang="ts">
  import '@material/web/progress/circular-progress.js';

  let {
    title,
    busy,
    status,
    children
  } = $props<{
    title: string;
    busy: boolean;
    status: string;
    children?: import('svelte').Snippet;
  }>();
</script>

<div class="workbench">
  <header class="page-header">
    <h2>{title}</h2>
    <span class="status {busy ? 'busy' : ''}" style="display: flex; align-items: center; padding: 0">
      {#if busy}
        <md-circular-progress 
          indeterminate 
          style="--md-circular-progress-size: 30px;"
        ></md-circular-progress>
      {:else}
        {status}
      {/if}
    </span>
  </header>
  <div class="workbench-content">
    {@render children?.()}
  </div>
</div>

// src/pages/workbench/WorkbenchShell.tsx
import type { ReactNode } from 'react';
import '@material/web/progress/circular-progress.js';

export function WorkbenchShell({ title, busy, status, children }: { title: string; busy: boolean; status: string; children: ReactNode }) {
  return (
    <div className="workbench">
      <header className="page-header">
        <h2>{title}</h2>
        <span className={busy ? 'status busy' : 'status'} style={{ display: 'flex', alignItems: 'center', padding:0}}>
          {busy ? (
            <>
              <md-circular-progress 
                indeterminate 
                style={{ '--md-circular-progress-size': '30px' } as React.CSSProperties}
              ></md-circular-progress>
            </>
          ) : (
            status
          )}
        </span>
      </header>
      <div className="workbench-content">{children}</div>
    </div>
  );
}
