// src/components/layout/DeviceStateScreen.svelte
<script lang="ts">
  import { i18n } from '../../locales/index.svelte';
  import MaterialIcon from '../MaterialIcon.svelte';
  import './DeviceStateScreen.css';

  let {
    serial,
    loading = false,
    children
  } = $props<{
    serial: string | null;
    loading?: boolean;
    children?: import('svelte').Snippet;
  }>();
</script>

{#if !serial}
  <div class="device-state-screen empty">
    <MaterialIcon name="phonelink_off" size={48} class="device-state-icon" />
    <h2>{i18n.t('common.device.empty.title')}</h2>
    <p>{i18n.t('common.device.empty.desc')}</p>
  </div>
{:else}
  {#if loading}
    <div class="device-state-screen loading">
      <md-circular-progress indeterminate></md-circular-progress>
    </div>
  {/if}
  <div style="display: {loading ? 'none' : 'contents'}">
    {@render children?.()}
  </div>
{/if}

// src/components/layout/DeviceStateScreen.tsx
import type { ReactNode } from 'react';
import { useI18n } from '../../locales';
import { MaterialIcon } from '../MaterialIcon';
import './DeviceStateScreen.css';

export type DeviceStateScreenProps = {
  serial: string | null;
  loading?: boolean;
  children: ReactNode;
};

export function DeviceStateScreen({ serial, loading, children }: DeviceStateScreenProps) {
  const { t } = useI18n();

  if (!serial) {
    return (
      <div className="device-state-screen empty">
        <MaterialIcon name="phonelink_off" size={48} className="device-state-icon" />
        <h2>{t('common.device.empty.title')}</h2>
        <p>{t('common.device.empty.desc')}</p>
      </div>
    );
  }

  return (
    <>
      {loading && (
        <div className="device-state-screen loading">
          <md-circular-progress indeterminate></md-circular-progress>
        </div>
      )}
      <div style={{ display: loading ? 'none' : 'contents' }}>
        {children}
      </div>
    </>
  );
}
