// src/components/layout/TopBar.tsx
import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { getName } from '@tauri-apps/api/app';
import { useDevices } from '../../context/DeviceContext';
import { useI18n } from '../../locales';
import { WirelessDialog } from '../dialogs/WirelessDialog';
import { MaterialIcon } from '../MaterialIcon';
import { DeviceSelector } from './DeviceSelector';
import './TopBar.css';

type DesktopPlatform = 'windows' | 'macos' | 'linux';

function detectPlatform(): DesktopPlatform {
  const platform = navigator.platform.toLowerCase();
  if (platform.includes('mac')) return 'macos';
  if (platform.includes('linux')) return 'linux';
  return 'windows';
}

export function TopBar() {
  const { t } = useI18n();
  const { devices, selectedDevice, loading, refreshDevices, selectDevice } = useDevices();
  const [wirelessOpen, setWirelessOpen] = useState(false);
  const [tcpipBusy, setTcpipBusy] = useState(false);
  const [maximized, setMaximized] = useState(false);
  const [appName, setAppName] = useState('ADB App');
  const platform = detectPlatform();
  const appWindow = getCurrentWindow();

  useEffect(() => {
    getName().then(setAppName).catch(() => {});
    void appWindow.isMaximized().then(setMaximized);
    const unlisten = appWindow.onResized(() => void appWindow.isMaximized().then(setMaximized));
    return () => { void unlisten.then(stop => stop()); };
  }, []);

  const connectUsbOverTcpip = async () => {
    if (!selectedDevice || tcpipBusy) return;
    setTcpipBusy(true);
    try {
      await invoke<string>('connect_usb_over_tcpip', { serial: selectedDevice.serial });
      await refreshDevices();
    } finally {
      setTcpipBusy(false);
    }
  };

  const windowControls = <div className="topbar__window-controls">
    <button className="topbar__window-control minimize" onClick={() => appWindow.minimize()} title={t('topbar.window.minimize')}><MaterialIcon name="remove" /></button>
    <button className="topbar__window-control maximize" onClick={async () => { await appWindow.toggleMaximize(); setMaximized(await appWindow.isMaximized()); }} title={maximized ? t('topbar.window.restore') : t('topbar.window.maximize')}><MaterialIcon name={maximized ? 'filter_none' : 'crop_square'} /></button>
    <button className="topbar__window-control close" onClick={() => appWindow.close()} title={t('topbar.window.close')}><MaterialIcon name="close" /></button>
  </div>;

  return <>
    <header className={`topbar topbar--${platform}`} data-tauri-drag-region onDoubleClick={() => appWindow.toggleMaximize()}>
      {platform === 'macos' && windowControls}
      <div className="topbar__identity" data-tauri-drag-region><img src="/icon.webp" alt="" /><h1 data-tauri-drag-region>{appName}</h1></div>
      <div className="topbar__drag-zone" data-tauri-drag-region />
      <div className="topbar__device-section" onDoubleClick={event => event.stopPropagation()}>
        <button className="topbar__tcpip" disabled={!selectedDevice || selectedDevice.state !== 'device' || (selectedDevice.serial.includes(':') || selectedDevice.serial.includes('._tcp')) || tcpipBusy} onClick={connectUsbOverTcpip} title={t('topbar.tcpip.tooltip')}><MaterialIcon name="usb" /><MaterialIcon name="arrow_forward" /><MaterialIcon name="wifi" /></button>
        <DeviceSelector devices={devices} selectedDevice={selectedDevice} loading={loading} loadingLabel={t('common.loading')} emptyLabel={t('common.noData')} onSelect={selectDevice} onDisconnect={async (serial) => {
          await invoke('disconnect_wireless_device', { endpoint: serial });
          await refreshDevices();
        }} />
        <button className={`topbar__wireless ${wirelessOpen ? 'active' : ''}`} onClick={() => setWirelessOpen(true)} title={t('topbar.wireless.tooltip')}><MaterialIcon name="add" /></button>
        <button className="topbar__action-btn" onClick={() => refreshDevices()} disabled={loading} title={t('main.refresh')}><MaterialIcon name="refresh" className={loading ? 'topbar__refresh-icon--spinning' : ''} /></button>
      </div>
      <div className="topbar__drag-zone" data-tauri-drag-region />
      {platform !== 'macos' && windowControls}
    </header>
    <WirelessDialog open={wirelessOpen} onClose={() => setWirelessOpen(false)} />
  </>;
}

// src/components/layout/TopBar.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { invoke } from '@tauri-apps/api/core';
  import { getCurrentWindow } from '@tauri-apps/api/window';
  import { getName } from '@tauri-apps/api/app';
  import { devicesState } from '../../context/devices.svelte';
  import { i18n } from '../../locales/index.svelte';
  import WirelessDialog from '../dialogs/WirelessDialog.svelte';
  import MaterialIcon from '../MaterialIcon.svelte';
  import DeviceSelector from './DeviceSelector.svelte';
  import './TopBar.css';

  let { adbAvailable = true } = $props<{ adbAvailable?: boolean }>();

  type DesktopPlatform = 'windows' | 'macos' | 'linux';

  function detectPlatform(): DesktopPlatform {
    const platform = navigator.platform.toLowerCase();
    if (platform.includes('mac')) return 'macos';
    if (platform.includes('linux')) return 'linux';
    return 'windows';
  }

  let wirelessOpen = $state(false);
  let tcpipBusy = $state(false);
  let maximized = $state(false);
  let appName = $state('ADB App');
  
  const platform = detectPlatform();
  const appWindow = getCurrentWindow();

  onMount(() => {
    getName().then(name => appName = name).catch(() => {});
    appWindow.isMaximized().then(m => maximized = m);
    
    let unlistenFn: (() => void) | null = null;
    appWindow.onResized(() => {
      appWindow.isMaximized().then(m => maximized = m);
    }).then(unlisten => {
      unlistenFn = unlisten;
    });
    
    return () => { 
      if (unlistenFn) unlistenFn(); 
    };
  });

  async function connectUsbOverTcpip() {
    if (!devicesState.selectedDevice || tcpipBusy) return;
    tcpipBusy = true;
    try {
      await invoke<string>('connect_usb_over_tcpip', { serial: devicesState.selectedDevice.serial });
      await devicesState.refreshDevices();
    } finally {
      tcpipBusy = false;
    }
  }

  async function handleDisconnect(serial: string) {
    await invoke('disconnect_wireless_device', { endpoint: serial });
    await devicesState.refreshDevices();
  }
</script>

<header class="topbar topbar--{platform}" data-tauri-drag-region ondblclick={() => appWindow.toggleMaximize()}>
  {#if platform !== 'macos'}
    <div class="topbar__identity" data-tauri-drag-region>
      <img src="/icon.webp" alt="" />
      <h1 data-tauri-drag-region>{appName}</h1>
    </div>
  {/if}
  
  <div class="topbar__drag-zone" data-tauri-drag-region></div>
  
  <div class="topbar__device-section" ondblclick={e => e.stopPropagation()}>
    <button 
      class="topbar__tcpip" 
      disabled={!devicesState.selectedDevice || devicesState.selectedDevice.state !== 'device' || (devicesState.selectedDevice.serial.includes(':') || devicesState.selectedDevice.serial.includes('._tcp')) || tcpipBusy} 
      onclick={connectUsbOverTcpip} 
      title={i18n.t('topbar.tcpip.tooltip')}
    >
      <MaterialIcon name="usb" />
      <MaterialIcon name="arrow_forward" />
      <MaterialIcon name="wifi" />
    </button>
    
    <DeviceSelector 
      devices={devicesState.devices} 
      selectedDevice={devicesState.selectedDevice} 
      loading={devicesState.loading} 
      loadingLabel={i18n.t('common.loading')} 
      emptyLabel={i18n.t('common.device.empty.title')} 
      onSelect={(serial) => devicesState.selectDevice(serial)} 
      onDisconnect={handleDisconnect} 
    />
    
    <button 
      class="topbar__wireless {wirelessOpen ? 'active' : ''}" 
      onclick={() => wirelessOpen = true} 
      title={i18n.t('topbar.wireless.tooltip')} 
      disabled={!adbAvailable}
    >
      <MaterialIcon name="add" />
    </button>
  </div>
  
  <div class="topbar__drag-zone" data-tauri-drag-region></div>
  
  {#if platform !== 'macos'}
    <div class="topbar__window-controls">
      <button class="topbar__window-control minimize" onclick={() => appWindow.minimize()} title={i18n.t('topbar.window.minimize')}>
        <MaterialIcon name="remove" />
      </button>
      <button class="topbar__window-control maximize" onclick={async () => { await appWindow.toggleMaximize(); maximized = await appWindow.isMaximized(); }} title={maximized ? i18n.t('topbar.window.restore') : i18n.t('topbar.window.maximize')}>
        <MaterialIcon name={maximized ? 'filter_none' : 'crop_square'} />
      </button>
      <button class="topbar__window-control close" onclick={() => appWindow.close()} title={i18n.t('topbar.window.close')}>
        <MaterialIcon name="close" />
      </button>
    </div>
  {/if}
</header>

<WirelessDialog open={wirelessOpen} onClose={() => {
  wirelessOpen = false;
  devicesState.refreshDevices();
}} />
