// src/pages/SettingsPage.svelte
<script lang="ts" module>
import * as m from '../paraglide/messages';

  export type ConfigurableTool = 'adb' | 'scrcpy' | 'java';
  export type InstallableTool = 'adb' | 'scrcpy';
</script>

<script lang="ts">
  import { onMount } from 'svelte';
  import { getVersion, getName } from '@tauri-apps/api/app';
  import { open } from '@tauri-apps/plugin-dialog';
  import type { ToolStatus, ToolsStatus } from './workbench/types';
  
  import MaterialIcon from '../components/MaterialIcon.svelte';
  import AppModal from '../components/dialogs/AppModal.svelte';
  import { APACHE_LICENSE_2_0, MIT_LICENSE } from '../utils/licenseTexts';
  import './SettingsPage.css';

  let {
    theme,
    language,
    tools,
    checkingUpdates,
    adbPath,
    scrcpyPath,
    javaPath,
    onThemeChange,
    onLanguageChange,
    onAdbPathChange,
    onScrcpyPathChange,
    onJavaPathChange,
    onSaveToolPath,
    onInstallTool,
    onClearCache,
    appSettings,
    onSaveAppSettings,
    defaultCacheDir
  } = $props<{
    theme: 'light' | 'dark' | 'auto';
    language: 'es' | 'en';
    tools: ToolsStatus | null;
    checkingUpdates: boolean;
    adbPath: string;
    scrcpyPath: string;
    javaPath: string;
    onThemeChange: (theme: 'light' | 'dark' | 'auto') => void;
    onLanguageChange: (language: 'es' | 'en') => void;
    onAdbPathChange: (path: string) => void;
    onScrcpyPathChange: (path: string) => void;
    onJavaPathChange: (path: string) => void;
    onSaveToolPath: (tool: ConfigurableTool, path: string) => void;
    onInstallTool: (tool: InstallableTool) => void;
    onClearCache: () => void;
    appSettings: { cache_enabled: boolean; cache_path: string; kill_adb_on_exit: boolean; theme: string; language: string } | null;
    onSaveAppSettings: (settings: { cache_enabled: boolean; cache_path: string; kill_adb_on_exit: boolean; theme: string; language: string }) => void;
    defaultCacheDir: string;
  }>();

  let appVersion = $state('...');
  let appName = $state('ADB App');
  let localCachePath = $state<string | null>(null);
  let licensesOpen = $state(false);

  type LicenseInfo = { name: string; url: string; licenseType: string; licenseText: string };
  const LICENSES: LicenseInfo[] = [
    { name: 'ADB', url: 'https://android.googlesource.com/platform/packages/modules/adb/', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'scrcpy', url: 'https://github.com/Genymobile/scrcpy', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Bundletool', url: 'https://github.com/google/bundletool', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Material Web', url: 'https://github.com/material-components/material-web', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Tauri', url: 'https://github.com/tauri-apps/tauri', licenseType: 'MIT / Apache 2.0', licenseText: MIT_LICENSE + '\n\n---\n\n' + APACHE_LICENSE_2_0 },
    { name: 'Svelte', url: 'https://github.com/sveltejs/svelte', licenseType: 'MIT License', licenseText: MIT_LICENSE }
  ];

  onMount(() => {
    getVersion().then(v => appVersion = v).catch(() => appVersion = 'Unknown');
    getName().then(n => appName = n).catch(() => {});
  });

  $effect(() => {
    if (appSettings && localCachePath === null) {
      localCachePath = appSettings.cache_path;
    }
  });

  function getToolStateLabel(tool: ToolStatus, checking: boolean) {
    if (!tool.available) return m.settings_notInstalled();
    if (tool.update_available) return m.settings_updateAvailable();
    if (checking) return m.settings_checkingUpdate();
    if (tool.update_checked) return m.settings_updated();
    return m.settings_checkFailed();
  }

  function getToolIconName(tool: ToolStatus, checking: boolean) {
    if (!tool.available) return 'close';
    if (tool.update_available) return 'new_releases';
    if (checking) return 'sync';
    if (tool.update_checked) return 'check_circle';
    return 'help';
  }

  async function pickDirectory(onChange: (p: string) => void) {
    const selected = await open({ directory: true, multiple: false });
    if (selected && typeof selected === 'string') {
      onChange(selected);
    }
  }
</script>

<div class="work-grid">
  
  <section class="md3-card">
    <h3 class="md3-title">{m.settings_appearance()}</h3>
    <div class="settings-appearance-row">
      <div class="md3-segmented-button">
        <button class={theme === 'light' ? 'active' : ''} onclick={() => onThemeChange('light')}>
          <MaterialIcon name="light_mode" />
          <span>{m.settings_theme_light()}</span>
        </button>
        <button class={theme === 'dark' ? 'active' : ''} onclick={() => onThemeChange('dark')}>
          <MaterialIcon name="dark_mode" />
          <span>{m.settings_theme_dark()}</span>
        </button>
        <button class={theme === 'auto' ? 'active' : ''} onclick={() => onThemeChange('auto')}>
          <MaterialIcon name="brightness_auto" />
          <span>{m.settings_theme_auto()}</span>
        </button>
      </div>

      <md-outlined-select 
        label={m.settings_language()}
        value={language} 
        onchange={(e: any) => onLanguageChange(e.target.value)}
      >
        <md-select-option value="es">
          <div slot="headline">Español</div>
        </md-select-option>
        <md-select-option value="en">
          <div slot="headline">English</div>
        </md-select-option>
      </md-outlined-select>
    </div>
  </section>
  
  {#snippet toolPanel(title: string, toolName: InstallableTool, tool: ToolStatus | undefined, path: string, placeholder: string, onChange: (p: string) => void)}
    <section class="md3-card">
      <h3 class="md3-title">{title}</h3>
      {#if tool}
        <div class="tool-status">
          <div class="tool-status-header">
            <MaterialIcon 
              name={getToolIconName(tool, checkingUpdates)} 
              size={20} 
              style={!tool.available ? 'color: var(--md-sys-color-error)' : ''}
            />
            <strong style={!tool.available ? 'color: var(--md-sys-color-error)' : ''}>
              {getToolStateLabel(tool, checkingUpdates)}
            </strong>
          </div>
          <div class="tool-status-details">
            <span>{m.settings_source()}: {tool.source || '-'}</span>
            <span>{m.settings_installedVersion()}: {tool.version || '-'}</span>
            {#if tool.latest_version}
              <span>{m.settings_latestVersion()}: {tool.latest_version}</span>
            {/if}
          </div>
        </div>
      {/if}
      <div class="form-stack">
        <md-outlined-text-field
          value={path}
          oninput={(e: any) => onChange(e.target.value)}
          label={placeholder}
          style="width: 100%"
        >
          <md-icon-button slot="trailing-icon" onclick={() => pickDirectory(onChange)}>
            <MaterialIcon name="folder_open" />
          </md-icon-button>
        </md-outlined-text-field>
        <div class="button-row">
          <md-filled-button onclick={() => onSaveToolPath(toolName, path)}>
            {m.settings_savePath()}
          </md-filled-button>
          <md-outlined-button onclick={() => onSaveToolPath(toolName, '')}>
            {m.settings_autoDetect()}
          </md-outlined-button>
          
          {#if tool?.install_supported && !tool.available}
            <md-filled-button onclick={() => onInstallTool(toolName)}>
              <MaterialIcon name="download" slot="icon" />
              {m.settings_install()} {title.split(' ')[0]}
            </md-filled-button>
          {/if}
          {#if tool?.install_supported && tool.update_available}
            <md-filled-button onclick={() => onInstallTool(toolName)}>
              <MaterialIcon name="update" slot="icon" />
              {m.settings_update()} {title.split(' ')[0]}
            </md-filled-button>
          {/if}
        </div>
      </div>
    </section>
  {/snippet}

  {@render toolPanel("ADB", "adb", tools?.adb, adbPath, m.settings_adbPlaceholder(), onAdbPathChange)}
  {@render toolPanel("scrcpy", "scrcpy", tools?.scrcpy, scrcpyPath, m.settings_scrcpyPlaceholder(), onScrcpyPathChange)}
  
  <section class="md3-card">
    <h3 class="md3-title">{m.settings_javaTitle()}</h3>
    <div class="tool-status">
      <div class="tool-status-header">
        <MaterialIcon 
          name={tools?.java.available ? 'check_circle' : 'warning'} 
          size={20} 
        />
        <strong>{tools?.java.available ? m.settings_javaCompatible() : tools?.java.path ? m.settings_javaNotCompatible() : m.settings_javaNotDetected()}</strong>
      </div>
      <div class="tool-status-details">
        <span>{m.settings_installedVersion()}: {tools?.java.version || '-'}</span>
      </div>
    </div>
    <div class="form-stack">
      <md-outlined-text-field 
        value={javaPath} 
        oninput={(e: any) => onJavaPathChange(e.target.value)} 
        label={m.settings_javaPlaceholder()}
        style="width: 100%"
      >
        <md-icon-button slot="trailing-icon" onclick={() => pickDirectory(onJavaPathChange)}>
          <MaterialIcon name="folder_open" />
        </md-icon-button>
      </md-outlined-text-field>
      <div class="button-row">
        <md-filled-button onclick={() => onSaveToolPath('java', javaPath)}>{m.settings_savePath()}</md-filled-button>
        <md-outlined-button onclick={() => onSaveToolPath('java', '')}>{m.settings_autoDetect()}</md-outlined-button>
        <md-text-button href="https://adoptium.net/es/temurin/releases" target="_blank" rel="noreferrer">
          <MaterialIcon name="open_in_new" slot="icon" />
          {m.settings_downloadTemurin()}
        </md-text-button>
      </div>
    </div>
  </section>
  
  <section class="md3-card">
    <h3 class="md3-title">{m.settings_cacheTitle()}</h3>
    <div class="form-stack">          
      <label class="settings-switch-row">
        <span class="md3-body-large">{m.settings_enableCache()}</span>
        <!-- svelte-ignore a11y_missing_attribute -->
        <md-switch 
          selected={appSettings?.cache_enabled ?? true ? true : undefined}
          onchange={(e: any) => {
            if (appSettings) {
              onSaveAppSettings({ ...appSettings, cache_enabled: e.target.selected });
            }
          }}
        ></md-switch>
      </label>

      <md-outlined-text-field 
        value={localCachePath || appSettings?.cache_path || defaultCacheDir} 
        oninput={(e: any) => localCachePath = e.target.value} 
        label={m.settings_cachePathPlaceholder()}
        style="width: 100%"
      >
        <md-icon-button slot="trailing-icon" onclick={() => pickDirectory((p) => localCachePath = p)}>
          <MaterialIcon name="folder_open" />
        </md-icon-button>
      </md-outlined-text-field>

      <div class="button-row settings-cache-actions" style="margin-top: 16px">
        <md-filled-button onclick={() => {
          if (appSettings && localCachePath !== null) {
            onSaveAppSettings({ ...appSettings, cache_path: localCachePath });
          }
        }}>
          {m.settings_savePath()}
        </md-filled-button>

        <md-outlined-button onclick={() => {
          if (appSettings) {
            localCachePath = '';
            onSaveAppSettings({ ...appSettings, cache_path: '' });
          }
        }}>
          {m.common_reset()}
        </md-outlined-button>

        <md-outlined-button onclick={onClearCache}>
          <MaterialIcon name="delete" slot="icon" />
          {m.common_clearCache()}
        </md-outlined-button>
      </div>
      <p style="font-size: 13px; color: var(--md-sys-color-error); margin-top: 8px; display: flex; align-items: center; gap: 6px; margin: 8px 0 0 0">
        <MaterialIcon name="info" size={16} />
        {m.settings_cacheRestartWarning()}
      </p>
    </div>
  </section>

  <section class="md3-card">
    <h3 class="md3-title">{m.settings_advancedTitle()}</h3>
    <div class="form-stack">          
      <label class="settings-switch-row">
        <span class="md3-body-large">{m.settings_killAdbOnExit()}</span>
        <!-- svelte-ignore a11y_missing_attribute -->
        <md-switch 
          selected={appSettings?.kill_adb_on_exit ?? true ? true : undefined}
          onchange={(e: any) => {
            if (appSettings) {
              onSaveAppSettings({ ...appSettings, kill_adb_on_exit: e.target.selected });
            }
          }}
        ></md-switch>
      </label>
    </div>
  </section>

  <section class="md3-card" style="grid-column: 1 / -1">
    <h3 class="md3-title">{m.settings_aboutTitle()}</h3>
    <div style="display: flex; flex-direction: column; align-items: flex-start; gap: 20px; text-align: left; padding: 16px 0">
      
      <div style="display: flex; width: 100%; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 16px">
        <div style="display: flex; align-items: center; gap: 16px">
          <img src="/icon.webp" style="width: 64px; height: 64px; pointer-events: none" alt="ADB App" />
          <div style="display: flex; flex-direction: column; justify-content: center">
            <h2 style="margin: 0 0 2px 0; font-size: 24px; line-height: 1.2">{appName}</h2>
            <span style="color: var(--md-sys-color-on-surface-variant); font-size: 14px">{appVersion}</span>
          </div>
        </div>
        <div style="display: flex; gap: 8px">
          <!-- svelte-ignore a11y_missing_attribute -->
          <md-filled-button href="https://github.com/kyro206/ADB-App" target="_blank" rel="noreferrer">
            <MaterialIcon name="code" slot="icon" />
            GitHub
          </md-filled-button>
          <md-outlined-button onclick={() => licensesOpen = true}>
            <MaterialIcon name="gavel" slot="icon" />
            {m.settings_aboutLicenses()}
          </md-outlined-button>
        </div>
      </div>

      <p style="font-size: 13px; color: var(--md-sys-color-error); display: flex; align-items: center; gap: 6px; margin: 0 0 8px 0">
        <MaterialIcon name="warning" size={16} />
        {m.settings_aboutDisclaimer()}
      </p>
      
      <div style="display: flex; align-items: center; gap: 12px; width: 100%">
        <div style="position: relative">
          <img 
            src="https://github.com/kyro206.png?size=200" 
            alt="Kyro206" 
            style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover; background: var(--md-sys-color-surface-variant)"
            onerror={(e) => {
              (e.currentTarget as HTMLElement).style.display = 'none';
              if (e.currentTarget.nextElementSibling) {
                (e.currentTarget.nextElementSibling as HTMLElement).style.display = 'flex';
              }
            }}
          />
          <div style="display: none; width: 40px; height: 40px; border-radius: 50%; background: var(--md-sys-color-surface-variant); align-items: center; justify-content: center; color: var(--md-sys-color-on-surface-variant)">
            <MaterialIcon name="person" size={24} />
          </div>
        </div>
        <div style="display: flex; flex-direction: column">
          <span style="font-size: 12px; color: var(--md-sys-color-on-surface-variant)">
            {m.settings_aboutCreator()}
          </span>
          <div style="display: flex; align-items: center; gap: 6px">
            <strong style="font-size: 15px; color: var(--md-sys-color-on-surface)">Kyro206</strong>
            <!-- svelte-ignore a11y_missing_attribute -->
            <md-icon-button href="https://github.com/kyro206" target="_blank" rel="noopener noreferrer" title="GitHub Profile">
              <MaterialIcon name="open_in_new" size={16} />
            </md-icon-button>
          </div>
        </div>
      </div>
      
    </div>
  </section>
  <AppModal open={licensesOpen} onClose={() => licensesOpen = false} title={m.settings_aboutLicenses()} width="large">
    <div style="display: flex; flex-direction: column; gap: 24px">
      <div style="background: var(--md-sys-color-surface-container); padding: 16px; border-radius: 12px; overflow-y: auto; border: 1px solid var(--md-sys-color-outline-variant)">
        {#each LICENSES as lic, index}
          <div style="margin-bottom: {index === LICENSES.length - 1 ? '0' : '32px'}">
            <div style="border-bottom: 1px dashed var(--md-sys-color-outline-variant); padding-bottom: 8px; margin-bottom: 12px">
              <h4 style="margin: 0 0 4px 0; font-size: 16px; color: var(--md-sys-color-on-surface); display: flex; align-items: center; justify-content: space-between">
                {lic.name}
                <!-- svelte-ignore a11y_missing_attribute -->
                <md-icon-button href={lic.url} target="_blank" rel="noopener noreferrer" title="Código original">
                  <MaterialIcon name="open_in_new" size={18} />
                </md-icon-button>
              </h4>
              <span style="font-size: 12px; color: var(--md-sys-color-on-surface-variant)">{lic.licenseType}</span>
            </div>
            <div style="font-size: 12px; font-family: monospace; white-space: pre-wrap; color: var(--md-sys-color-on-surface-variant)">
              {lic.licenseText}
            </div>
          </div>
        {/each}
      </div>
    </div>
  </AppModal>
</div>

// src/pages/SettingsPage.tsx
import { useState, useEffect } from 'react';
import type { ReactNode } from 'react';
import type { ToolStatus, ToolsStatus } from './workbench/types';
import { getVersion, getName } from '@tauri-apps/api/app';
import { MaterialIcon } from '../components/MaterialIcon';
import { open } from '@tauri-apps/plugin-dialog';
import './SettingsPage.css';

import { useI18n } from '../locales';
import { AppModal } from '../components/dialogs/AppModal';
import { APACHE_LICENSE_2_0, MIT_LICENSE } from '../utils/licenseTexts';

// --- COMPONENTES BASE MD3 ---

function Panel({ title, children, style, className }: { title: string; children: ReactNode; style?: React.CSSProperties; className?: string }) {
  return (
    <section className={`md3-card ${className || ''}`} style={style}>
      <h3 className="md3-title">{title}</h3>
      {children}
    </section>
  );
}

function ToolState({ tool, checking, t }: { tool: ToolStatus; checking: boolean; t: (key: string, params?: Record<string, string | number>) => string }) {
  const state = !tool.available
    ? t('settings.notInstalled')
    : tool.update_available
      ? t('settings.updateAvailable')
      : checking
        ? t('settings.checkingUpdate')
        : tool.update_checked
          ? t('settings.updated')
          : t('settings.checkFailed');

  const iconName = !tool.available
    ? 'error'
    : tool.update_available
      ? 'new_releases'
      : checking
        ? 'sync'
        : tool.update_checked
          ? 'check_circle'
          : 'help';

  return (
    <div className="tool-status">
      <div className="tool-status-header">
        <MaterialIcon name={iconName} size={20} />
        <strong>{state}</strong>
      </div>
      <div className="tool-status-details">
        <span>{t('settings.source')}: {tool.source || '-'}</span>
        <span>{t('settings.installedVersion')}: {tool.version || '-'}</span>
        {tool.latest_version && <span>{t('settings.latestVersion')}: {tool.latest_version}</span>}
      </div>
    </div>
  );
}

// --- TIPOS ---
type ConfigurableTool = 'adb' | 'scrcpy' | 'java';
type InstallableTool = 'adb' | 'scrcpy';

type ToolPanelProps = {
  title: string;
  toolName: InstallableTool;
  tool?: ToolStatus;
  path: string;
  placeholder: string;
  checking: boolean;
  t: (key: string, params?: Record<string, string | number>) => string;
  onPathChange: (path: string) => void;
  onSave: (tool: ConfigurableTool, path: string) => void;
  onInstall: (tool: InstallableTool) => void;
  children?: ReactNode;
};

function ToolPanel(props: ToolPanelProps) {
  const { t, toolName } = props;
  const shortTitle = props.title.split(' ')[0];

  return (
    <Panel title={props.title}>
      {props.tool && <ToolState tool={props.tool} checking={props.checking} t={t} />}
      <div className="form-stack">
        <md-outlined-text-field
          value={props.path}
          onInput={(e: any) => props.onPathChange(e.target.value)}
          label={props.placeholder}
          style={{ width: '100%' }}
        >
          <md-icon-button slot="trailing-icon" onClick={async () => {
            const selected = await open({ directory: true, multiple: false });
            if (selected && typeof selected === 'string') {
              props.onPathChange(selected);
            }
          }}>
            <MaterialIcon name="folder_open" />
          </md-icon-button>
        </md-outlined-text-field>
        <div className="button-row">
          <md-filled-button onClick={() => props.onSave(toolName, props.path)}>
            {t('settings.savePath')}
          </md-filled-button>
          <md-outlined-button onClick={() => props.onSave(toolName, '')}>
            {t('settings.autoDetect')}
          </md-outlined-button>
          
          {props.tool?.install_supported && !props.tool.available && (
            <md-filled-button onClick={() => props.onInstall(toolName)}>
              <MaterialIcon name="download" slot="icon" />
              {t('settings.install')} {shortTitle}
            </md-filled-button>
          )}
          {props.tool?.install_supported && props.tool.update_available && (
            <md-filled-button onClick={() => props.onInstall(toolName)}>
              <MaterialIcon name="update" slot="icon" />
              {t('settings.update')} {shortTitle}
            </md-filled-button>
          )}
        </div>
        {props.children}
      </div>
    </Panel>
  );
}

// --- PÁGINA PRINCIPAL ---

type SettingsPageProps = {
  theme: 'light' | 'dark' | 'auto';
  language: 'es' | 'en';
  tools: ToolsStatus | null;
  checkingUpdates: boolean;
  adbPath: string;
  scrcpyPath: string;
  javaPath: string;
  onThemeChange: (theme: 'light' | 'dark' | 'auto') => void;
  onLanguageChange: (language: 'es' | 'en') => void;
  onAdbPathChange: (path: string) => void;
  onScrcpyPathChange: (path: string) => void;
  onJavaPathChange: (path: string) => void;
  onSaveToolPath: (tool: ConfigurableTool, path: string) => void;
  onInstallTool: (tool: InstallableTool) => void;
  onClearCache: () => void;
  appSettings: { cache_enabled: boolean; cache_path: string; kill_adb_on_exit: boolean; theme: string; language: string } | null;
  onSaveAppSettings: (settings: { cache_enabled: boolean; cache_path: string; kill_adb_on_exit: boolean; theme: string; language: string }) => void;
  defaultCacheDir: string;
};

export function SettingsPage(props: SettingsPageProps) {
  const { theme, language, tools, checkingUpdates } = props;
  const { t } = useI18n();
  const [appVersion, setAppVersion] = useState<string>('...');
  const [appName, setAppName] = useState('ADB App');
  const [localCachePath, setLocalCachePath] = useState<string | null>(null);
  
  type LicenseInfo = { name: string; url: string; licenseType: string; licenseText: string };
  const [licensesOpen, setLicensesOpen] = useState(false);

  const LICENSES: LicenseInfo[] = [
    { name: 'ADB', url: 'https://android.googlesource.com/platform/packages/modules/adb/', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'scrcpy', url: 'https://github.com/Genymobile/scrcpy', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Bundletool', url: 'https://github.com/google/bundletool', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Material Web', url: 'https://github.com/material-components/material-web', licenseType: 'Apache License 2.0', licenseText: APACHE_LICENSE_2_0 },
    { name: 'Tauri', url: 'https://github.com/tauri-apps/tauri', licenseType: 'MIT / Apache 2.0', licenseText: MIT_LICENSE + '\n\n---\n\n' + APACHE_LICENSE_2_0 },
    { name: 'React', url: 'https://github.com/facebook/react', licenseType: 'MIT License', licenseText: MIT_LICENSE }
  ];

  useEffect(() => {
    getVersion().then(setAppVersion).catch(() => setAppVersion('Unknown'));
    getName().then(setAppName).catch(() => {});
  }, []);

  useEffect(() => {
    if (props.appSettings && localCachePath === null) {
      setLocalCachePath(props.appSettings.cache_path);
    }
  }, [props.appSettings, localCachePath]);

  return (
    <div className="work-grid">
      
      {/* TARJETA DE APARIENCIA E IDIOMA */}
      <Panel title={t('settings.appearance')}>
        <div className="settings-appearance-row">
          <div className="md3-segmented-button">
            {[
              ['light_mode', t('settings.theme.light'), 'light'],
              ['dark_mode', t('settings.theme.dark'), 'dark'],
              ['brightness_auto', t('settings.theme.auto'), 'auto']
            ].map(([icon, label, value]) => (
              <button key={value} className={theme === value ? 'active' : ''} onClick={() => props.onThemeChange(value as any)}>
                <MaterialIcon name={icon} />
                <span>{label}</span>
              </button>
            ))}
          </div>

          <md-outlined-select 
            label={t('settings.language')}
            value={language} 
            onChange={(e: any) => props.onLanguageChange(e.target.value as 'es' | 'en')}
          >
            <md-select-option value="es">
              <div slot="headline">Español</div>
            </md-select-option>
            <md-select-option value="en">
              <div slot="headline">English</div>
            </md-select-option>
          </md-outlined-select>
        </div>
      </Panel>
      
      {/* TARJETAS DE HERRAMIENTAS */}
      <ToolPanel 
        title="ADB" 
        toolName="adb" 
        tool={tools?.adb} 
        path={props.adbPath} 
        placeholder={t('settings.adbPlaceholder')} 
        checking={checkingUpdates} 
        t={t}
        onPathChange={props.onAdbPathChange} 
        onSave={props.onSaveToolPath} 
        onInstall={props.onInstallTool} 
      />
      
      <ToolPanel 
        title="scrcpy" 
        toolName="scrcpy" 
        tool={tools?.scrcpy} 
        path={props.scrcpyPath} 
        placeholder={t('settings.scrcpyPlaceholder')} 
        checking={checkingUpdates} 
        t={t}
        onPathChange={props.onScrcpyPathChange} 
        onSave={props.onSaveToolPath} 
        onInstall={props.onInstallTool} 
      />
      
      {/* TARJETA DE JAVA */}
      <Panel title={t('settings.javaTitle')}>
        <div className="tool-status">
          <div className="tool-status-header">
            <MaterialIcon 
              name={tools?.java.available ? 'check_circle' : 'warning'} 
              size={20} 
            />
            <strong>{tools?.java.available ? t('settings.javaCompatible') : tools?.java.path ? t('settings.javaNotCompatible') : t('settings.javaNotDetected')}</strong>
          </div>
          <div className="tool-status-details">
            <span>{t('settings.installedVersion')}: {tools?.java.version || '-'}</span>
          </div>
        </div>
        <div className="form-stack">
          <md-outlined-text-field 
            value={props.javaPath} 
            onInput={(e: any) => props.onJavaPathChange(e.target.value)} 
            label={t('settings.javaPlaceholder')}
            style={{ width: '100%' }}
          >
            <md-icon-button slot="trailing-icon" onClick={async () => {
              const selected = await open({ directory: true, multiple: false });
              if (selected && typeof selected === 'string') {
                props.onJavaPathChange(selected);
              }
            }}>
              <MaterialIcon name="folder_open" />
            </md-icon-button>
          </md-outlined-text-field>
          <div className="button-row">
            <md-filled-button onClick={() => props.onSaveToolPath('java', props.javaPath)}>{t('settings.savePath')}</md-filled-button>
            <md-outlined-button onClick={() => props.onSaveToolPath('java', '')}>{t('settings.autoDetect')}</md-outlined-button>
            <md-text-button href="https://adoptium.net/es/temurin/releases" target="_blank" rel="noreferrer">
              <MaterialIcon name="open_in_new" slot="icon" />
              {t('settings.downloadTemurin')}
            </md-text-button>
          </div>
        </div>
      </Panel>
      
      {/* TARJETA DE CACHÉ */}
      <Panel title={t('settings.cacheTitle')}>
        <div className="form-stack">          
          <label className="settings-switch-row">
            <span className="md3-body-large">{t('settings.enableCache')}</span>
            <md-switch 
              selected={props.appSettings?.cache_enabled ?? true}
              onChange={(e: any) => {
                if (props.appSettings) {
                  props.onSaveAppSettings({ ...props.appSettings, cache_enabled: e.target.selected });
                }
              }}
            />
          </label>

          <md-outlined-text-field 
            value={localCachePath || props.appSettings?.cache_path || props.defaultCacheDir} 
            onInput={(e: any) => setLocalCachePath(e.target.value)} 
            label={t('settings.cachePathPlaceholder')}
            style={{ width: '100%' }}
          >
            <md-icon-button slot="trailing-icon" onClick={async () => {
              const selected = await open({ directory: true, multiple: false });
              if (selected && typeof selected === 'string') {
                setLocalCachePath(selected);
              }
            }}>
              <MaterialIcon name="folder_open" />
            </md-icon-button>
          </md-outlined-text-field>

          <div className="button-row settings-cache-actions" style={{ marginTop: '16px' }}>
            <md-filled-button onClick={() => {
              if (props.appSettings && localCachePath !== null) {
                props.onSaveAppSettings({ ...props.appSettings, cache_path: localCachePath });
              }
            }}>
              {t('settings.savePath')}
            </md-filled-button>

            <md-outlined-button onClick={() => {
              if (props.appSettings) {
                setLocalCachePath('');
                props.onSaveAppSettings({ ...props.appSettings, cache_path: '' });
              }
            }}>
              {t('common.reset')}
            </md-outlined-button>

            <md-outlined-button onClick={props.onClearCache}>
              <MaterialIcon name="delete" slot="icon" />
              {t('common.clearCache')}
            </md-outlined-button>
          </div>
          <p style={{ fontSize: '13px', color: 'var(--md-sys-color-error)', marginTop: '8px', display: 'flex', alignItems: 'center', gap: '6px', margin: '8px 0 0 0' }}>
            <MaterialIcon name="info" size={16} />
            {t('settings.cacheRestartWarning')}
          </p>
        </div>
      </Panel>

      {/* TARJETA DE OPCIONES AVANZADAS */}
      <Panel title={t('settings.advancedTitle')}>
        <div className="form-stack">          
          <label className="settings-switch-row">
            <span className="md3-body-large">{t('settings.killAdbOnExit')}</span>
            <md-switch 
              selected={props.appSettings?.kill_adb_on_exit ?? true}
              onChange={(e: any) => {
                if (props.appSettings) {
                  props.onSaveAppSettings({ ...props.appSettings, kill_adb_on_exit: e.target.selected });
                }
              }}
            />
          </label>
        </div>
      </Panel>

      {/* ACERCA DE */}
      <Panel title={t('settings.aboutTitle')} style={{ gridColumn: '1 / -1' }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '20px', textAlign: 'left', padding: '16px 0' }}>
          
          {/* Cabecera (Icono, Nombre, Versión, Botón GitHub) */}
          <div style={{ display: 'flex', width: '100%', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
              <img src="/icon.webp" style={{ width: '64px', height: '64px', pointerEvents: 'none' }} alt="ADB App" />
              <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <h2 style={{ margin: '0 0 2px 0', fontSize: '24px', lineHeight: '1.2' }}>{appName}</h2>
                <span style={{ color: 'var(--md-sys-color-on-surface-variant)', fontSize: '14px' }}>{appVersion}</span>
              </div>
            </div>
            <div style={{ display: 'flex', gap: '8px' }}>
              <md-filled-button href="https://github.com/kyro206/ADB-App" target="_blank" rel="noreferrer">
                <MaterialIcon name="code" slot="icon" />
                GitHub
              </md-filled-button>
              <md-outlined-button onClick={() => setLicensesOpen(true)}>
                <MaterialIcon name="gavel" slot="icon" />
                {t('settings.aboutLicenses')}
              </md-outlined-button>
            </div>
          </div>

          {/* Aviso de responsabilidad */}
          <p style={{ fontSize: '13px', color: 'var(--md-sys-color-error)', display: 'flex', alignItems: 'center', gap: '6px', margin: '0 0 8px 0' }}>
            <MaterialIcon name="warning" size={16} />
            {t('settings.aboutDisclaimer')}
          </p>
          
          {/* Creador */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', width: '100%' }}>
            <div style={{ position: 'relative' }}>
              <img 
                src="https://github.com/kyro206.png?size=200" 
                alt="Kyro206" 
                style={{ width: '40px', height: '40px', borderRadius: '50%', objectFit: 'cover', background: 'var(--md-sys-color-surface-variant)' }}
                onError={(e) => {
                  e.currentTarget.style.display = 'none';
                  if (e.currentTarget.nextElementSibling) {
                    (e.currentTarget.nextElementSibling as HTMLElement).style.display = 'flex';
                  }
                }}
              />
              <div style={{ display: 'none', width: '40px', height: '40px', borderRadius: '50%', background: 'var(--md-sys-color-surface-variant)', alignItems: 'center', justifyContent: 'center', color: 'var(--md-sys-color-on-surface-variant)' }}>
                <MaterialIcon name="person" size={24} />
              </div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              <span style={{ fontSize: '12px', color: 'var(--md-sys-color-on-surface-variant)' }}>
                {t('settings.aboutCreator')}
              </span>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <strong style={{ fontSize: '15px', color: 'var(--md-sys-color-on-surface)' }}>Kyro206</strong>
                <md-icon-button href="https://github.com/kyro206" target="_blank" rel="noopener noreferrer" title="GitHub Profile">
                  <MaterialIcon name="open_in_new" size={16} />
                </md-icon-button>
              </div>
            </div>
          </div>
          
        </div>
      </Panel>
      <AppModal open={licensesOpen} onClose={() => setLicensesOpen(false)} title={t('settings.aboutLicenses')} width="large">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

          <div style={{ 
            background: 'var(--md-sys-color-surface-container)', 
            padding: '16px', 
            borderRadius: '12px', 
            overflowY: 'auto',
            border: '1px solid var(--md-sys-color-outline-variant)'
          }}>
            {LICENSES.map((lic, index) => (
              <div key={lic.name} style={{ marginBottom: index === LICENSES.length - 1 ? 0 : '32px' }}>
                <div style={{ borderBottom: '1px dashed var(--md-sys-color-outline-variant)', paddingBottom: '8px', marginBottom: '12px' }}>
                  <h4 style={{ margin: '0 0 4px 0', fontSize: '16px', color: 'var(--md-sys-color-on-surface)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    {lic.name}
                    <md-icon-button href={lic.url} target="_blank" rel="noopener noreferrer" title="Código original">
                      <MaterialIcon name="open_in_new" size={18} />
                    </md-icon-button>
                  </h4>
                  <span style={{ fontSize: '12px', color: 'var(--md-sys-color-on-surface-variant)' }}>{lic.licenseType}</span>
                </div>
                <div style={{ fontSize: '12px', fontFamily: 'monospace', whiteSpace: 'pre-wrap', color: 'var(--md-sys-color-on-surface-variant)' }}>
                  {lic.licenseText}
                </div>
              </div>
            ))}
          </div>
        </div>
      </AppModal>
    </div>
  );
}
