// src/components/dialogs/AppModal.tsx
import { useEffect, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useI18n } from '../../locales';
import { MaterialIcon } from '../MaterialIcon';
import './AppModal.css';

type AppModalProps = {
  open: boolean;
  title: string;
  subtitle?: string;
  children: ReactNode;
  actions?: ReactNode;
  onClose: () => void;
  width?: 'compact' | 'medium' | 'large';
};

export function AppModal({ open, title, subtitle, children, actions, onClose, width = 'medium' }: AppModalProps) {
  const { t } = useI18n();

  useEffect(() => {
    if (!open) return;
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [onClose, open]);

  if (!open) return null;

  return createPortal(
    <div className="app-modal-layer" onDoubleClick={event => event.stopPropagation()}>
      <div className="app-modal-scrim" onClick={onClose} aria-hidden="true" />
      <section className={`app-modal app-modal--${width}`} role="dialog" aria-modal="true" aria-labelledby="app-modal-title" onClick={event => event.stopPropagation()}>
        <md-elevation />
        <header className="app-modal__header">
          <div><h2 id="app-modal-title">{title}</h2>{subtitle && <p>{subtitle}</p>}</div>
          <md-icon-button aria-label={t('common.close')} onClick={onClose}><MaterialIcon name="close" /></md-icon-button>
        </header>
        <div className="app-modal__content">{children}</div>
        {actions && <footer className="app-modal__actions">{actions}</footer>}
      </section>
    </div>,
    document.body,
  );
}

// src/components/dialogs/AppModal.svelte
<script lang="ts">
  import { onMount, type Snippet } from 'svelte';
  import { i18n } from '../../locales/index.svelte';
  import MaterialIcon from '../MaterialIcon.svelte';
  import './AppModal.css';

  let {
    open = false,
    title,
    subtitle = '',
    width = 'medium',
    onClose,
    children,
    actions
  } = $props<{
    open: boolean;
    title: string;
    subtitle?: string;
    width?: 'compact' | 'medium' | 'large';
    onClose: () => void;
    children?: Snippet;
    actions?: Snippet;
  }>();

  onMount(() => {
    const closeOnEscape = (event: KeyboardEvent) => {
      if (open && event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  });
</script>

{#if open}
  <div class="app-modal-layer" ondblclick={e => e.stopPropagation()}>
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="app-modal-scrim" onclick={onClose} aria-hidden="true"></div>
    
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <section 
      class="app-modal app-modal--{width}" 
      role="dialog" 
      aria-modal="true" 
      aria-labelledby="app-modal-title" 
      onclick={e => e.stopPropagation()}
    >
      <md-elevation></md-elevation>
      <header class="app-modal__header">
        <div>
          <h2 id="app-modal-title">{title}</h2>
          {#if subtitle}
            <p>{subtitle}</p>
          {/if}
        </div>
        <md-icon-button aria-label={i18n.t('common.close')} onclick={onClose}>
          <MaterialIcon name="close" />
        </md-icon-button>
      </header>
      
      <div class="app-modal__content">
        {@render children?.()}
      </div>
      
      {#if actions}
        <footer class="app-modal__actions">
          {@render actions()}
        </footer>
      {/if}
    </section>
  </div>
{/if}
