// src/components/dialogs/WirelessDialog.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { invoke } from '@tauri-apps/api/core';
  import { devicesState } from '../../context/devices.svelte';
  import { i18n } from '../../locales/index.svelte';
  import MaterialIcon from '../MaterialIcon.svelte';
  import AppModal from './AppModal.svelte';
  import './WirelessDialog.css';

  let { open = false, onClose } = $props<{ open: boolean; onClose: () => void }>();

  type WirelessMode = 'connect' | 'pair' | 'qr';
  type WirelessQrPayload = { service_name: string; password: string; qr_data_url: string };

  let mode = $state<WirelessMode>('connect');
  let busy = $state(false);
  let status = $state('');
  let connectEndpoint = $state('');
  let pairEndpoint = $state('');
  let pairCode = $state('');
  let qrPayload = $state<WirelessQrPayload | null>(null);

  let genId = 0;

  async function run(command: string, payload: Record<string, unknown>, pending: string, success: string) {
    busy = true;
    status = pending;
    try { 
      const oldDevices = await invoke<any[]>('list_devices').catch(() => []);
      status = await invoke<string>(command, payload) || success; 
      const newDevices = await invoke<any[]>('list_devices').catch(() => []);
      
      const newDevice = newDevices.find(nd => !oldDevices.some(od => od.serial === nd.serial));
      await devicesState.refreshDevices(newDevice?.serial);
      
      onClose();
    }
    catch (error) { status = String(error); }
    finally { busy = false; }
  }

  async function generateQr() {
    genId++;
    const currentGen = genId;
    busy = true;
    status = i18n.t('wireless.status.generatingQr');
    let payload: WirelessQrPayload | null = null;
    try { 
      payload = await invoke<WirelessQrPayload>('generate_wireless_qr');
      if (mode === 'qr' && open && currentGen === genId) {
        qrPayload = payload; 
      }
    }
    catch (error) { 
      if (mode === 'qr' && open && currentGen === genId) {
        status = String(error); 
        busy = false; 
      }
      return; 
    }
    
    if (payload && mode === 'qr' && open && currentGen === genId) {
      status = i18n.t('wireless.status.scanQr');
      try {
        const oldDevices = await invoke<any[]>('list_devices').catch(() => []);
        await invoke<string>('pair_wireless_qr', { serviceName: payload.service_name, password: payload.password });
        const newDevices = await invoke<any[]>('list_devices').catch(() => []);
        
        const newDevice = newDevices.find(nd => !oldDevices.some(od => od.serial === nd.serial));
        await devicesState.refreshDevices(newDevice?.serial);
        
        if (open && currentGen === genId) {
          onClose();
        }
      } catch (error) {
        if (mode === 'qr' && open && currentGen === genId) {
          generateQr();
        }
      }
    }
  }

  $effect(() => {
    if (open && status === '') status = i18n.t('wireless.status.ready');
    if (mode === 'qr' && !qrPayload && !busy) {
      generateQr();
    }
  });
</script>

<AppModal {open} {onClose} title={i18n.t('wireless.title')}>
  <md-tabs class="wireless-tabs">
    <md-primary-tab active={mode === 'connect' ? true : undefined} onclick={() => mode = 'connect'}>
      {i18n.t('wireless.tab.connect')}
    </md-primary-tab>
    <md-primary-tab active={mode === 'pair' ? true : undefined} onclick={() => mode = 'pair'}>
      {i18n.t('wireless.tab.code')}
    </md-primary-tab>
    <md-primary-tab active={mode === 'qr' ? true : undefined} onclick={() => {
      if (mode === 'qr') generateQr();
      else mode = 'qr';
    }}>
      {i18n.t('wireless.tab.qr')}
    </md-primary-tab>
  </md-tabs>
  
  {#if mode === 'connect'}
    <section class="wireless-form">
      <p>{i18n.t('wireless.connect.desc')}</p>
      <md-outlined-text-field 
        label={i18n.t('wireless.connect.endpoint')} 
        value={connectEndpoint} 
        oninput={(e: any) => connectEndpoint = e.target.value} 
      ></md-outlined-text-field>
      <md-filled-button 
        disabled={!connectEndpoint.trim() || busy ? true : undefined} 
        onclick={() => run('connect_wireless_device', { endpoint: connectEndpoint }, i18n.t('wireless.connect.pending'), i18n.t('wireless.connect.success'))}
      >
        {i18n.t('wireless.tab.connect')}
      </md-filled-button>
    </section>
  {/if}
  
  {#if mode === 'pair'}
    <section class="wireless-form">
      <p>{i18n.t('wireless.pair.desc')}</p>
      <md-outlined-text-field 
        label={i18n.t('wireless.pair.endpoint')} 
        value={pairEndpoint} 
        oninput={(e: any) => pairEndpoint = e.target.value} 
      ></md-outlined-text-field>
      <md-outlined-text-field 
        label={i18n.t('wireless.pair.code')} 
        value={pairCode} 
        oninput={(e: any) => pairCode = e.target.value} 
      ></md-outlined-text-field>
      <md-filled-button 
        disabled={!pairEndpoint.trim() || !pairCode.trim() || busy ? true : undefined} 
        onclick={() => run('pair_wireless_device', { endpoint: pairEndpoint, code: pairCode }, i18n.t('wireless.pair.pending'), i18n.t('wireless.pair.success'))}
      >
        {i18n.t('wireless.action.pair')}
      </md-filled-button>
    </section>
  {/if}
  
  {#if mode === 'qr'}
    <section class="wireless-qr">
      <div class="wireless-qr__preview">
        {#if qrPayload}
          <img src={qrPayload.qr_data_url} alt={i18n.t('wireless.qr.alt')} />
        {:else}
          <MaterialIcon name="qr_code_2" />
        {/if}
      </div>
      <div>
        <p>{i18n.t('wireless.qr.desc')}</p>
      </div>
    </section>
  {/if}
  
  <div class="wireless-status">
    {#if busy}
      <md-circular-progress indeterminate></md-circular-progress>
    {:else}
      <MaterialIcon name="check_circle" filled />
    {/if}
    <span>{status}</span>
  </div>
</AppModal>

// src/components/dialogs/WirelessDialog.tsx
import { useState, useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { useDevices } from '../../context/DeviceContext';
import { useI18n } from '../../locales';
import { MaterialIcon } from '../MaterialIcon';
import { AppModal } from './AppModal';
import './WirelessDialog.css';

type WirelessMode = 'connect' | 'pair' | 'qr';
type WirelessQrPayload = { service_name: string; password: string; qr_data_url: string };

export function WirelessDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { t } = useI18n();
  const { refreshDevices } = useDevices();
  const [mode, setMode] = useState<WirelessMode>('connect');
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState('');
  const [connectEndpoint, setConnectEndpoint] = useState('');
  const [pairEndpoint, setPairEndpoint] = useState('');
  const [pairCode, setPairCode] = useState('');
  const [qrPayload, setQrPayload] = useState<WirelessQrPayload | null>(null);

  const modeRef = useRef(mode);
  const openRef = useRef(open);
  const genIdRef = useRef(0);

  useEffect(() => { modeRef.current = mode; }, [mode]);
  useEffect(() => { openRef.current = open; }, [open]);

  const run = async (command: string, payload: Record<string, unknown>, pending: string, success: string) => {
    setBusy(true); setStatus(pending);
    try { 
      const oldDevices = await invoke<any[]>('list_devices').catch(() => []);
      setStatus(await invoke<string>(command, payload) || success); 
      const newDevices = await invoke<any[]>('list_devices').catch(() => []);
      
      const newDevice = newDevices.find(nd => !oldDevices.some(od => od.serial === nd.serial));
      await refreshDevices(newDevice?.serial);
      
      onClose();
    }
    catch (error) { setStatus(String(error)); }
    finally { setBusy(false); }
  };
  
  const generateQr = async () => {
    const currentGen = ++genIdRef.current;
    setBusy(true); setStatus(t('wireless.status.generatingQr'));
    let payload: WirelessQrPayload | null = null;
    try { 
      payload = await invoke<WirelessQrPayload>('generate_wireless_qr');
      if (modeRef.current === 'qr' && openRef.current && currentGen === genIdRef.current) {
        setQrPayload(payload); 
      }
    }
    catch (error) { 
      if (modeRef.current === 'qr' && openRef.current && currentGen === genIdRef.current) {
        setStatus(String(error)); 
        setBusy(false); 
      }
      return; 
    }
    
    if (payload && modeRef.current === 'qr' && openRef.current && currentGen === genIdRef.current) {
      setStatus(t('wireless.status.scanQr'));
      try {
        const oldDevices = await invoke<any[]>('list_devices').catch(() => []);
        await invoke<string>('pair_wireless_qr', { serviceName: payload.service_name, password: payload.password });
        const newDevices = await invoke<any[]>('list_devices').catch(() => []);
        
        const newDevice = newDevices.find(nd => !oldDevices.some(od => od.serial === nd.serial));
        await refreshDevices(newDevice?.serial);
        
        if (openRef.current && currentGen === genIdRef.current) {
          onClose();
        }
      } catch (error) {
        // Auto-refresh if it failed (timeout) and we are still in QR mode
        if (modeRef.current === 'qr' && openRef.current && currentGen === genIdRef.current) {
          generateQr();
        }
      }
    }
  };

  // Efecto para autogenerar el código QR al entrar en la pestaña correspondiente
  useEffect(() => {
    if (open && status === '') setStatus(t('wireless.status.ready'));
    if (mode === 'qr' && !qrPayload && !busy) {
      generateQr();
    }
  }, [mode, qrPayload, open, status, busy, t]);

  return <AppModal open={open} onClose={onClose} title={t('wireless.title')}>
    <md-tabs className="wireless-tabs">
      <md-primary-tab active={mode === 'connect' || undefined} onClick={() => setMode('connect')}>{t('wireless.tab.connect')}</md-primary-tab>
      <md-primary-tab active={mode === 'pair' || undefined} onClick={() => setMode('pair')}>{t('wireless.tab.code')}</md-primary-tab>
      <md-primary-tab active={mode === 'qr' || undefined} onClick={() => {
        if (mode === 'qr') generateQr();
        else setMode('qr');
      }}>{t('wireless.tab.qr')}</md-primary-tab>
    </md-tabs>
    
    {mode === 'connect' && <section className="wireless-form">
      <p>{t('wireless.connect.desc')}</p>
      <md-outlined-text-field label={t('wireless.connect.endpoint')} value={connectEndpoint} onInput={(event: any) => setConnectEndpoint(event.currentTarget.value)} />
      <md-filled-button disabled={!connectEndpoint.trim() || busy || undefined} onClick={() => run('connect_wireless_device', { endpoint: connectEndpoint }, t('wireless.connect.pending'), t('wireless.connect.success'))}>{t('wireless.tab.connect')}</md-filled-button>
    </section>}
    
    {mode === 'pair' && <section className="wireless-form">
      <p>{t('wireless.pair.desc')}</p>
      <md-outlined-text-field label={t('wireless.pair.endpoint')} value={pairEndpoint} onInput={(event: any) => setPairEndpoint(event.currentTarget.value)} />
      <md-outlined-text-field label={t('wireless.pair.code')} value={pairCode} onInput={(event: any) => setPairCode(event.currentTarget.value)} />
      <md-filled-button disabled={!pairEndpoint.trim() || !pairCode.trim() || busy || undefined} onClick={() => run('pair_wireless_device', { endpoint: pairEndpoint, code: pairCode }, t('wireless.pair.pending'), t('wireless.pair.success'))}>{t('wireless.action.pair')}</md-filled-button>
    </section>}
    
    {mode === 'qr' && <section className="wireless-qr">
      <div className="wireless-qr__preview">
        {qrPayload ? <img src={qrPayload.qr_data_url} alt={t('wireless.qr.alt')} /> : <MaterialIcon name="qr_code_2" />}
      </div>
      <div>
        <p>{t('wireless.qr.desc')}</p>
      </div>
    </section>}
    
    <div className="wireless-status">{busy ? <md-circular-progress indeterminate /> : <MaterialIcon name="check_circle" filled />}<span>{status}</span></div>
  </AppModal>;
}
